In [27]:
import numpy as np
import pandas as pd
import re

In [141]:
# 轨道系数 C
CM=pd.read_csv('DATA.csv').to_numpy()
pd.DataFrame(CM)

,0,1,2,3,4,5,6,7,8,9
0,0.70235,0.70327,-0.16698,-0.18922,0.00000,-0.07466,0.00000,0.00000,0.00000,0.09041
1,0.02242,0.01421,0.55914,0.78778,0.00000,0.35632,0.00000,0.00000,0.00000,-0.55397
2,0.00000,0.00000,0.00000,0.00000,0.65959,0.00000,0.00000,0.00000,0.76663,0.00000
3,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.65959,0.76663,0.00000,0.00000
4,-0.00653,0.00031,-0.20061,0.13638,0.00000,0.60631,0.00000,0.00000,0.00000,0.94266
5,-0.70235,0.70327,-0.16698,0.18922,0.00000,-0.07466,0.00000,0.00000,0.00000,-0.09041
6,-0.02242,0.01421,0.55914,-0.78778,0.00000,0.35632,0.00000,0.00000,0.00000,0.55397
7,0.00000,0.00000,0.00000,0.00000,0.65959,0.00000,0.00000,0.00000,-0.76663,0.00000
8,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.65959,-0.76663,0.00000,0.00000
9,-0.00653,-0.00031,0.20061,0.13638,0.00000,-0.60631,0.00000,0.00000,0.00000,0.94266

In [142]:
np.sum(CM[0,:8]**2)*2

2.1142897196

In [143]:
# 密度矩阵 P(自己计算的)
P=np.zeros((10,10))
n=np.array([2]*8+[0]*2)
for i in range(10):
    C1=CM[:,i][:,np.newaxis]
    C2=CM[:,i][np.newaxis,:]
    P+=C1*C2*n[i]
pd.DataFrame(P)

,0,1,2,3,4,5,6,7,8,9
0,2.114290,-0.486583,0.000000,0.000000,-0.083887,-0.002109,0.046685,0.000000,0.000000,-0.037682
1,-0.486583,2.121807,0.000000,0.000000,0.422333,0.046685,-0.362593,0.000000,0.000000,0.006831
2,0.000000,0.000000,0.870118,0.000000,0.000000,0.000000,0.000000,0.870118,0.000000,0.000000
3,0.000000,0.000000,0.000000,2.045561,0.000000,0.000000,0.000000,0.000000,-0.305325,0.000000
4,-0.083887,0.422333,0.000000,0.000000,0.852997,0.037682,-0.006831,0.000000,0.000000,-0.778428
5,-0.002109,0.046685,0.000000,0.000000,0.037682,2.114290,-0.486583,0.000000,0.000000,0.083887
6,0.046685,-0.362593,0.000000,0.000000,-0.006831,-0.486583,2.121807,0.000000,0.000000,-0.422333
7,0.000000,0.000000,0.870118,0.000000,0.000000,0.000000,0.000000,0.870118,0.000000,0.000000
8,0.000000,0.000000,0.000000,-0.305325,0.000000,0.000000,0.000000,0.000000,2.045561,0.000000
9,-0.037682,0.006831,0.000000,0.000000,-0.778428,0.083887,-0.422333,0.000000,0.000000,0.852997

In [152]:
# 重叠矩阵 S
overlapStr=\
"""0.100000D+01
0.236704D+00  0.100000D+01
0.000000D+00  0.000000D+00  0.100000D+01
0.000000D+00  0.000000D+00  0.000000D+00  0.100000D+01
0.000000D+00  0.000000D+00  0.000000D+00  0.000000D+00  0.100000D+01
0.000000D+00  0.222396D-01  0.000000D+00  0.000000D+00 -0.376360D-01 0.100000D+01
0.222396D-01  0.276700D+00  0.000000D+00  0.000000D+00 -0.317826D+00 0.236704D+00  0.100000D+01
0.000000D+00  0.000000D+00  0.149257D+00  0.000000D+00  0.000000D+00 0.000000D+00  0.000000D+00  0.100000D+01
0.000000D+00  0.000000D+00  0.000000D+00  0.149257D+00  0.000000D+00 0.000000D+00  0.000000D+00  0.000000D+00  0.100000D+01
0.376360D-01  0.317826D+00  0.000000D+00  0.000000D+00 -0.305811D+00 0.000000D+00  0.000000D+00  0.000000D+00  0.000000D+00  0.100000D+01"""
overList=[]
for line in overlapStr.split('\n'):
    data=re.split(' +',line)
    data=[float(each.replace('D','e')) for each in data]
    data+=[0.]*(10-len(data))
    overList.append(data)
overMatrix=np.array(overList)
S=np.tril(overMatrix)+np.tril(overMatrix,-1).T
pd.DataFrame(S)

,0,1,2,3,4,5,6,7,8,9
0,1.000000,0.236704,0.000000,0.000000,0.000000,0.000000,0.022240,0.000000,0.000000,0.037636
1,0.236704,1.000000,0.000000,0.000000,0.000000,0.022240,0.276700,0.000000,0.000000,0.317826
2,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.149257,0.000000,0.000000
3,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.149257,0.000000
4,0.000000,0.000000,0.000000,0.000000,1.000000,-0.037636,-0.317826,0.000000,0.000000,-0.305811
5,0.000000,0.022240,0.000000,0.000000,-0.037636,1.000000,0.236704,0.000000,0.000000,0.000000
6,0.022240,0.276700,0.000000,0.000000,-0.317826,0.236704,1.000000,0.000000,0.000000,0.000000
7,0.000000,0.000000,0.149257,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
8,0.000000,0.000000,0.000000,0.149257,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
9,0.037636,0.317826,0.000000,0.000000,-0.305811,0.000000,0.000000,0.000000,0.000000,1.000000

In [153]:
P12=P[0:5,5:10]
P21=P[5:10,0:5]
S12=S[0:5,5:10]
S21=S[5:10,0:5]
PS=P@S

In [154]:
np.sum(P12@S12@P21@S21)

0.014296237559321454

In [159]:
np.sum(PS[0:5,5:10]@PS[5:10,0:5])

1.3900763923559103

In [166]:
total=0
for a in range(0,5):
    for b in range(5,10):
        total+=PS[a,b]*PS[b,a]
total

1.999992380770856

In [175]:
np.sum(PS[0:5,5:10]*PS[5:10,0:5].T)

1.999992380770856

In [ ]:
import sympy

f=(2*a/pi)**(3/4)*2*(a)**0.5*e**(-a*(x**2+y**2+z**2)**0.5)